### ISSUE TITLE
Need access to SSH or deployment system

### ISSUE THREAD

**Issue by soapstain22** [jacylin873/Edu-Planner#14]
This will host our webspace.
Github has built in deployments using Actions, but if the server is going to be accessible we either need to use a domain, forward a port, or get access to the new paltz web server.
- [ ] https://webapps.newpaltz.edu/its/shellaccount

**Comment by jacylin873** [comment]
Requested access from the New Paltz IT department. Awaiting results.

**Comment by jacylin873** [comment]
domain URL is www2.newpaltz.edu/~linj41
