### ISSUE TITLE
XAMPP

### ISSUE THREAD

**Issue by soapstain22** [jacylin873/Edu-Planner#7]
[Downloading XAMPP](https://mylearning.suny.edu/d2l/le/content/830198/viewContent/24894190/View)
[Install XAMPP Windows](https://mylearning.suny.edu/d2l/le/content/830198/viewContent/24894191/View)
[Install XAMPP Mac OS X](https://mylearning.suny.edu/d2l/le/content/830198/viewContent/24894192/View)
[How to install XAMPP and Create XAMPP Control Panel Launcher on Ubuntu 18.04 LTS](https://mylearning.suny.edu/d2l/le/content/830198/viewContent/24894194/View)
[Working with the Apache Server](https://mylearning.suny.edu/d2l/le/content/830198/viewContent/24894195/View)
CONFIRM THAT YOU LOOKED INTO THESE

**Comment by angelfo7319** [comment]
Finished
